# Generated by Django 3.2.15 on 2024-09-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_alter_piemodel_num_of_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('office', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('startdate', models.DateField(null=True)),
                ('salary', models.CharField(max_length=15)),
            ],
        ),
    ]
