# Generated by Django 3.2.15 on 2024-09-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_tableapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Close_price', models.IntegerField(default=0)),
                ('Individual', models.IntegerField(default=0)),
                ('Foreigner', models.IntegerField(default=0)),
                ('Organ', models.IntegerField(default=0)),
                ('Finance', models.IntegerField(default=0)),
                ('Insurance', models.IntegerField(default=0)),
                ('Investment', models.IntegerField(default=0)),
                ('Bank', models.IntegerField(default=0)),
                ('Other_finance', models.IntegerField(default=0)),
                ('Pension_fund', models.IntegerField(default=0)),
                ('Other_corporations', models.IntegerField(default=0)),
                ('Other_foreiner', models.IntegerField(default=0)),
                ('Private_fund', models.IntegerField(default=0)),
            ],
        ),
    ]
