# Generated by Django 3.2.15 on 2024-09-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_samsung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samsung',
            name='Bank',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='Close_price',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='Finance',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='Foreigner',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='Individual',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='Insurance',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='Investment',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='Organ',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='Other_corporations',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='Other_finance',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='Other_foreiner',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='Pension_fund',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='Private_fund',
            field=models.TextField(default='0'),
        ),
    ]
