# Generated by Django 3.2.15 on 2024-09-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='thumbnail',
            new_name='profile_image',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
