# Generated by Django 3.2.15 on 2024-09-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='feed_id',
            new_name='Person_id',
        ),
    ]
