# Generated by Django 3.2.15 on 2024-09-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_feed_id_person_person_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='is_Person',
            new_name='is_person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Person_id',
            new_name='person_id',
        ),
    ]
