# Generated by Django 3.2.15 on 2024-09-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20240916_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person_id',
            new_name='follow_id',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='is_person',
            new_name='is_follow',
        ),
    ]
