# Generated by Django 3.2.15 on 2024-09-17 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20240916_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Follow',
        ),
    ]
